Squashed 'vendor/pybind11/' changes from 0bd8896a4..a2e59f0e7
a2e59f0e7 chore: bump to 2.13.6
e445ca2bd ci: PyPI attestations (#5374)
7b67d8e97 docs: update changelog for 2.13.6 (#5372)
a5fcc5602 Enable type-safe interoperability between different independent Python/C++ bindings systems. (#5296)
54ab42496 chore(deps): bump the actions group with 2 updates (#5361)
36ee4674f chore(deps): update pre-commit hooks (#5350)
9e6a67d57 Properly translate C++ exception to Python exception when creating Python buffer from wrapped object (#5324)
570d323bb Add `while True` & `top` method to FAQ. (#5340)
b9f85757d fix: using `__cpp_nontype_template_args` instead of `__cpp_nontype_template_parameter_class` (#5330)
0a96ff7e9 chore(deps): bump actions/attest-build-provenance in the actions group (#5335)
7c33cdc2d chore: prepare for 2.13.5
b3f5f2e74 docs: prepare for 2.13.5 (#5327)
a4f6627da docs: clarify requirements for including pybind11 (#5326)
0d21cadca fix: allow -Wpedantic in C++20 mode (#5322)
ff3ca7864 fix: `<ranges>` support for `py::tuple` and `py::list` (#5314)
b0050f30d fix: never use `..` in a header include (#5321)
c6239a8a1 chore: version 2.13.4
63b0d146d docs: prepare for 2.13.4 (#5312)
973a16e9a fix: escape paths with spaces in pybind11-config (#4874)
75c11769b Revert "fix: quote paths from pybind11-config (#5302)" (#5309)
6685547e3 chore: remove repetitive words (#5308)
bd6764365 chore: prepare for 2.13.3
7662af69c docs: prepare for 2.13.3
45eaee91d fix: quote paths from pybind11-config (#5302)
835139f5d fix: emscripten cmake issue (#5301)
07f30430d chore: prepare for 2.13.2
6d5704cd2 docs: prepare for 2.13.2 (#5299)
6ee574fab chore(deps): bump actions/attest-build-provenance in the actions group (#5297)
d8fcfe341 fix(cmake): add required emscripten flags (#5298)
78e26321c Add `type_caster_std_function_specializations` feature. (#4597)
44d0d9a41 chore(deps): update pre-commit hooks (#5288)
fe808a011 chore(deps): bump the actions group with 2 updates (#5287)
f9ae715d4 fix: typo in documentation (#5284)
042c3cfdc clang-tidy upgrade (to version 18) (#5272)
667563dd5 docs: remove outdated known limitation. (#5263)
129934ad9 Small cleanup/refactoring in support of PR #5213 (#5251)
f50830eae tests: run on pyodide (#4745)
b43074533 docs: extend `PYBIND11_MODULE` documentation, mention `mod_gil_not_used` (#5250)
f3a6d4145 fix: make gil_safe_call_once thread-safe in free-threaded CPython (#5246)
d699e99c5 chore(deps): bump actions/attest-build-provenance in the actions group (#5243)
4b2f7cd65 chore(deps): bump certifi from 2024.2.2 to 2024.7.4 in /docs (#5226)
8443d0841 Use PyMutex instead of std::mutex in free-threaded build. (#5219)
41726b643 chore(deps): update pre-commit hooks (#5220)
ea10a69da chore(deps): bump actions/attest-build-provenance in the actions group (#5216)
a4dd41a18 feat(types) Adds special Case for empty C++ tuple type annotation (#5214)
639ca6a71 Fixed a compilation error with gcc 14 (#5208)
65afa13eb fix: add guard for GCC <10.3 on C++20 (#5205)
3074608eb fix(cmake): remove extra = in flto assignment (#5207)
941f45bcb chore: prepare for 2.13.1
63020d336 docs: prepare for 2.13.1 (#5203)
dd0e4a0b8 feat(types): add support for Typing.Callable Special Case (#5202)
3b47b4648 fix: use manual padding of instance_map_shard (#5200)
0c69e1eb2 chore: prepare for 2.13.0 (#5198)
2be85c604 feat(types): adds support for TypeGuard and TypeIs (#5194)
b5ec7c717 ci: release with trusted publisher and attestations (#5196)
26281c798 feat(types): adds support for Never and NoReturn from python Typing (#5193)
183059f9a feat(types): add support for typing.Literal type (#5192)
aebcd704d Add TypeVars / method generics typing (#5167)
9ec64e37c docs: prepare for 2.13.0 (#5187)
a406a62e5 fix: use `std::addressof` in type_caster_base.h (#5189)
f1a2e03d1 feat: remove Python 3.6 support (#5177)
5552cbf20 Add Python 3.10, 3.11, 3.12 to win32 job matrix. (#5179)
186df220f docs: building suggestions update (#5168)
baa540ec3 fix: support free-threaded CPython with GIL disabled (#5148)
1961b96a8 chore(deps): bump urllib3 from 2.2.1 to 2.2.2 in /docs (#5170)
fdd20d69c chore(deps): bump seanmiddleditch/gha-setup-ninja in the actions group (#5169)
7c4ac91d7 Add type[T] support to typing.h (#5166)
68405a114 Add `Union` and `Optional` to typing.h (#5165)
ab955f158 Fix refcount bug involving trampoline functions with `PyObject *` return type. (#5156)
35ff42b56 Add a pybind function to clear a list. (#5153)
9b3a20006 fix(cmake): improved cross-compilation support (#5083)
b9794be43 chore(deps): update pre-commit hooks (#5154)
1a0ff4054 tests: avoid immortal objects in tests (#5150)
7187894e0 fix(cmake): old cmake boost bug (#5149)
ae6432b81 fix: Python 3.13t with GIL (#5139)
a5b9e50f6 fix: added check on iterator end position (#5129)
ce08e3704 fix: handle NULL correctly (#5145)
86a64290d chore: some cleanup (#5137)
4d0fcedc2 fix: support Python 3.13.0b1 (PEP 667 fix) (#5127)
b07fddb21 --- (#5130)
aa98d9571 chore(deps): update pre-commit hooks (#5123)
ede061ca0 chore(deps): bump the actions group with 1 update (#5082)
750257797 chore(deps): bump jinja2 from 3.1.3 to 3.1.4 in /docs (#5122)
c9747570f chore(deps): bump idna from 3.6 to 3.7 in /docs (#5121)
6497b3f2f docs(numpy): drop duplicated ndim (#5119)
a9256a6d2 chore: docs and nox bump (#5071)
f39847947 ci: macos-latest is changing to macos-14 ARM runners (#5109)
19a6b9f4e Fix typo in changelog date (#5096)
f33f6afb6 chore(deps): update pre-commit hooks (#5084)
7f2214bc6 chore: bump cmake to 3.29 (#5075)
7af193e7e chore: get back to work
b91b584da docs: remove extra space
3e9dfa286 docs: a few missed changes for 2.12 (#5074)
6b5674f36 chore: prepare 2.12.0 (#5070)
67c9c5687 fix: fully qualify usages of concat to protect against ADL (#4955)
0efff79f0 Bug fixes: Add missing `handle_type_name` specializations. (#5073)
705efccec feat: make `numpy.h` compatible with both NumPy 1.x and 2.x (#5050)
e0f2c7159 tests: hide warning on clang (#5069)
65370f330 Create handle_type_name specialization to type-hint variable length tuples (#5051)
ddb8b67a8 fix(cmake): allow forcing old FindPython (#5042)
ec73bdaf1 ci: skipping test for Windows Clang failure (#5062)
8b48ff878 chore(deps): bump the actions group with 3 updates (#5024)
0518bf9f9 ci: ignore actions/checkout until v5 comes out
e84d446d8 ci: Ignore v1 updates for checkout (#5023)
416f7a441 chore(deps): update pre-commit hooks (#5018)
768cebe17 doc: add litgen to the automatic generators list (compiling.rst) (#5012)
869cc1ff0 install mingw-w64-${{matrix.env}}-python-scipy only for mingw64 (#5006)
39e65e10d ci: group dependabot updates (#4986)
31b7e1405 bugfix: removing typing and duplicate ``class_`` for KeysView/ValuesView/ItemsView. Fix #4529 (#4985)
aec6cc540 fix(cmake): skip empty PYBIND11_PYTHON_EXECUTABLE_LAST for the first cmake run (#4856)
f29def9ea chore(deps): update pre-commit hooks (#4994)
b583336cf chore(deps): bump ilammy/msvc-dev-cmd from 1.12.1 to 1.13.0 (#4995)
976fea05a Fix Clazy warnings (#4988)
eeac2f457 chore(deps): bump actions/upload-artifact from 3 to 4 (#4975)
e8a43ea97 chore(deps): bump actions/download-artifact from 3 to 4 (#4976)
dc477fac0 fix: Use PyObject_VisitManagedDict() of Python 3.13 (#4973)
daea1130b fix(cmake): upgrade maximum supported CMake version to 3.27 (#4786)
7d538a427 fix: make_static_property_type() (#4971)
68322895d chore(deps): bump actions/setup-python from 4 to 5 (#4965)
c1e06f5bf chore(deps): update pre-commit hooks (#4963)
a67d78657 fix(stl_bind): Enable `bind_map` with `using` declarations. (#4952)
4bb6163b4 chore(deps): bump deadsnakes/action from 3.0.1 to 3.1.0 (#4951)
dc9b39596 pybind11.pc: use pcfiledir for relative destinations (#4830)
9591cfb0b fix(cmake): findpython issues and 3.12 support for pybind11_find_import (#4941)
6831666f5 ci: add more versions of numpy/scipy/pypy (#4714)
6cf90e728 fix(cmake): avoid really slow compile on emscripten (#4642)
b389ae77c chore: update changelog script for categories (#4942)
e250155af Fix a long-standing bug in the handling of Python multiple inheritance (#4762)
2c35fde38 Fix refcount bug introduced with PR #4916. (#4927)
c758b81f3 chore: move to ruff-format (#4912)
0a974fed5 chore(deps): update pre-commit hooks (#4923)
f2606930b Use newer PyCode API and other fixes (#4916)
31b0a5d94 fix doc typo
76b7f5364 Python_ADDITIONAL_VERSIONS: 3.12 (#4909)
a18c10f69 fix(cmake): make library component optional (#4805)
3aece819f chore: update hooks and Ruff config (#4904)
1e28599e4 fix: Add missing spaces to error string (#4906)
fa27d2fd4 Adapt to changed function name in Python 3.13 (#4902)
bf88e29c9 Bug fix: Replace bare `static exception<T>` with `gil_safe_call_once_and_store`. (#4897)
3414c56b6 Workaround NVCC parse failure in `cast_op` (#4893)
7969049de Comment out failing job, with link to #4889 (#4890)
74439a64a feature: Use typed iterators in `make_*iterator` (#4876)
0cbd92bab Update pytest to version 7.2.0 (which removes their dependency on py) (#4880)
0e2c3e5db Add pybind11/gil_safe_call_once.h (to fix deadlocks in pybind11/numpy.h) (#4877)
6c7720856 chore(deps): bump seanmiddleditch/gha-setup-ninja from 3 to 4 (#4875)
2b2e4ca4a chore(deps): update pre-commit hooks (#4868)
dd64df73c MAINT: Remove np.int_ (#4867)
0a756c0bb MAINT: Include `numpy._core` imports (#4857)
f468b0707 Add 2 missing `throw error_already_set();` (#4863)
7e5edbc94 Avoid copy in iteration by using const auto & (#4861)
5891867ee fix(cmake): support DEBUG_POSTFIX correctly (#4761)
4fb111bd7 fix(cmake): correctly detect FindPython policy and better warning (#4806)
d06d53694 Fix small bug introduced with PR #4735 (#4845)
8c7b8dd0a fix: Missing typed variants of `iterator` and `iterable` (#4832)
b4573674b Update render for buffer sequence and handle  (#4831)
c9149d995 fix: Use lowercase builtin collection names (#4833)
c83605936 feature: Support move-only iterators in `py::make_*iterator` (#4834)
4a2f7e468 chore(deps): bump actions/checkout from 1 to 4 (#4836)
467fe27bd chore(deps): update pre-commit hooks (#4838)
c9638a192 Help Coverty avoid generating a false positive. (#4817)
db412e6e8 fix: Render `py::function` as `Callable` (#4829)
e705fb5f2 Fix enum's `__str__` docstring (#4827)
1adac5a5b `PYBIND11_INTERNALS_VERSION` bump for MSVC, piggy-backed on PR #4779. See comments there. (#4819)
76b885811 fix: Different MSVC versions may be ABI incompatible, guard with _MSC_VER (#2898) (#4779)
b9359cead Remove newlines from docstring signature (#4735)
f47ff3280 Fix grammar in functions.rst (#4791)
80bcd21fb [ci skip] Adopt nanobind config. (#4792)
add281a2d Migrate to readthedocs configuration file v2¶ (#4789)
9039e6ac4 chore: use 2x faster black mirror (#4784)
4bf60c609 Disable strip when build type is unset (#4454) (#4780)
690a115d8 Add `py::set_error()`, use in updated `py::exception<>` documentation (#4772)
824dc27a0 CI: Reenable an NVHPC Test (#4764)
f8703154e Provide better type hints for a variety of generic types (#4259)
9ad7e827a docs: Remove upper bound on pybind11 in example pyproject.toml for setuptools (#4774)
413e6328d chore(deps): update pre-commit hooks (#4770)
17b614303 clang 17 compatibility fixes (#4767)
f3e060280 Add command to check for vX.Y.Z tag vs pybind11/_version.py consistency. (#4757)
8d08dc64c Copy v2.11.1 changelog section as released. (#4755)
99131a85b Provide `PYBIND11_NO_ASSERT_GIL_HELD_INCREF_DECREF` as an option (#4753)
ec1b57c50 Disable `PYBIND11_ASSERT_GIL_HELD_INCREF_DECREF` generally for PyPy (not just PyPy Windows). (#4751)
0620d7163 Update README.rst - Add missing comma in the list of acknowlegements (#4750)
e85696e80 Post release version bump (#4747)
1a917f185 docs: preparation for v2.11.0 release (#4744)
b33d06f61 bugfix: fixes a test suite bug in the __new__ example (#4698)
2e5f5c4cf fix: support CMake 3.27, drop 3.4 (#4719)
6d22dba82 Warning on comparing wrapper enums with is (#4732)
b2732c6e1 chore(deps): bump pypa/gh-action-pypi-publish from 1.8.6 to 1.8.7 (#4718)
47dc0c4bd chore(deps): update pre-commit hooks (#4727)
d462dd91a chore(deps): bump scipy from 1.8.0 to 1.10.0 in /tests (#4731)
782b6281a Drop PyPy 3.7 from GitHub Actions (ci.yml) (#4728)
5ccb9e412 chore: ruff moved to astral-sh (#4726)
2fb3d7cbd Trivial refactoring to make the capsule API more user friendly. (#4720)
e10da79b6 Undo ci.yml gcc10 workaround after docker-library/gcc#95 was resolved. (#4717)
bc1bcf7c0 chore: 3.12 + cleanup (#4713)
849322806 Systematically add `PIP_BREAK_SYSTEM_PACKAGES` to all .yml files from which pip is called. (#4705)
86f60a0c0 pre-commit markdown-it-py<3 (for Python 3.7 compatibility) (#4704)
0e43fcc75 Python 3.12b2 testing (#4695)
c679a9209 chore(deps): bump deadsnakes/action from 3.0.0 to 3.0.1 (#4687)
3617f3554 chore(deps): update pre-commit hooks (#4689)
29487dee8 Disable 🐍 3 • CentOS7 / PGI 22.9 • x64 (#4691)
d0232b119 Use annotated for array (#4679)
8e1f9d5c4 Add `format_descriptor<>` & `npy_format_descriptor<>` `PyObject *` specializations. (#4674)
6e6bcca5b Create s Security Policy (#4671)
ce9bbc0a2 Python 3.11+: Add `__notes__` to `error_already_set::what()` output. (#4678)
19816f0db chore: update changelog, with target date for v2.11.0 release (#4677)
d72ffb448 ci: set minimal permissions to github workflows (#4665)
cca4c51ca Update errors in string "Explicit conversions" docs (#4658)
e9b961d9b Elide to-python conversion of setter return values (#4621)
90312a6ee Add `type_caster<PyObject>` (#4601)
f70165463 Introduce recursive_container_traits (#4623)
b3e88ecf8 chore(deps): update pre-commit hooks (#4648)
dff75a62b chore(deps): bump pypa/gh-action-pypi-publish from 1.8.5 to 1.8.6 (#4650)
da9192629 fix: remove -stdlib=libc++ from setup helpers, not needed on modern Pythons (#4639)
956390a87 fix(cmake): only define lto if CMAKE's IPO setting is unset (#4643)
5e946c2fa chore(deps): update pre-commit hooks (#4605)
3f366ff88 Remove stray comment. (Oversight in PR #4631. Noticed by chance.) (#4641)
6de6191a0 Use `std::hash<std::type_index>`, `std::equal_to<std::type_index>` everywhere **except when libc++ is in use** (#4319)
ff7f5dfca 1. Fully test unstable ABI (#4635)
07725c28c Introduce `pybind11::detail::is_move_constructible` (#4631)
071f35ab8 chore(deps): bump jwlawson/actions-setup-cmake from 1.13 to 1.14 (#4632)
ed466da57 chore(deps): bump pypa/gh-action-pypi-publish from 1.8.4 to 1.8.5 (#4604)
7ab88d2e4 chore(deps): bump pypa/gh-action-pypi-publish from 1.8.3 to 1.8.4 (#4602)
4ce05175d ci: Python 3.12 optional test job (#4575)
654fe9265 Introduce `get_python_state_dict()` for Python 3.12 compatibility. (#4570)
1e8b52a9a bugfix: allow noexcept lambdas in C++17. Fix #4565 (#4593)
66f12df03 chore: make #4587 use proper cpp17 feature macro (#4592)
5bbcba548 use C++17 syntax to get rid of recursive template instantiations for concatenating type signatures (#4587)
286873ecf chore(deps): bump pypa/gh-action-pypi-publish from 1.8.1 to 1.8.3 (#4584)
cf7d2e6f1 Change `always_forkserver_on_unix()` to `use_multiprocessing_forkserver_on_linux()` (#4577)
c4c15d4b1 docs: changelog for 2.10.4 (#4532)
04ef4e422 chore(deps): bump pypa/gh-action-pypi-publish from 1.6.4 to 1.8.1 (#4576)
442261da5 Remove test code that does not exercise anything in pybind11, but breaks between Python 3.12alpha3 (still working) and 3.12alpha6 (broken): (#4559)
cbb876cc7 chore(deps): update pre-commit hooks (#4552)
3cc7e4258 add --version option to pybind11-config (#4526)
438034c5b chore: move to Ruff and add rules (#4483)
a19daeac1 Inconsistent comments between 2 templates of `unchecked()`. (#4519)
68211d41c fix: nicer stack level for warning (#4516)
6a5e6007c Make warning suppressions MINGW-specific again. (#4515)
d1956eabb Appease new flake8 B028 error: (#4513)
08a4a47a6 Revert "Go back to CMake 3.25.2 (#4496)" (#4503)
535f81a1c fix: tests dir has started to show up in packaging (#4510)
8dcced29a Always display python type information in cast errors (#4463)
531144ddd Replace "whitelist" with "allowlist" (#4506)
b8f28551c Go back to CMake 3.25.2 (#4496)
f8713ec43 Revert "bugfix: Keep registered types until after Py_Finalize(). Fix #4459 (#4486)" (#4501)
8a90b3677 chore(deps): update pre-commit hooks (#4495)
b2c1978ca bugfix: Keep registered types until after Py_Finalize(). Fix #4459 (#4486)
9ef65cee0 chore(deps): bump ilammy/msvc-dev-cmd from 1.12.0 to 1.12.1 (#4493)
08a89fac3 bugfix: delete proper ctors in gil.h (#4490)
3efe9d4cb chore: update to black 23 (#4482)
44e936822 Use PyConfig_InitPythonConfig instead of PyConfig_InitIsolatedConfig (#4473)
c71e3af73 Bump isort version to 5.12.0 (#4480)
a500f439d Resolve new flake8 error (#4462)
c709d2a83 Make sure to properly untrack gc objects before freeing them (#4461)
e53d58af6 Ensure `import pybind11_tests` traceback is shown. (#4455)
d821788bb Add clang15 C++20 job (#4443)
a34596bfe chore: back to work
b2d7ad72c chore: prepare for 2.10.3 (#4437)
769fd3b88 chore(deps): update pre-commit hooks (#4439)
e3e24f3f6 fix: issuses detected by static analyzer (#4440)
6da268a5c ci: remove clang 10 C++20 (it broke recently) (#4438)
f12e098f1 Fix `detail::obj_class_name()` to work correctly for meta classes. (#4436)
60f02f5f6 fix: improve the error reporting for inc_ref GIL failures (#4427)
70af9873c docs: fixed typo in spelling of first (#4428)
7f23e9f3a chore: update clang-tidy to 15 (#4387)
REVERT: 0bd8896a4 chore: prepare for 2.10.3 (#4437)
REVERT: d78de2952 chore(deps): update pre-commit hooks (#4439)
REVERT: 9d6a79c09 fix: issuses detected by static analyzer (#4440)
REVERT: 050de893c ci: remove clang 10 C++20 (it broke recently) (#4438)
REVERT: 0abe64c5f Fix `detail::obj_class_name()` to work correctly for meta classes. (#4436)
REVERT: e414c4bdd fix: improve the error reporting for inc_ref GIL failures (#4427)
REVERT: 2de6e398e [v2.10] Revert the addition of the GIL check feature (#4432)
REVERT: 037641780 Merge branch 'master' into v2.10
REVERT: 80dc998ef chore: bump versions for 2.10.1
REVERT: f2ee641ee docs: prepare for 2.10.1 release (#4279)
REVERT: 3fb36a99f fix: unicode surrogate character in Python exception message. (#4297)
REVERT: 15fde1def Add `PYBIND11_SIMPLE_GIL_MANAGEMENT` option (cmake, C++ define) (#4216)
REVERT: 5b395c9b4 fix: improve bytes to str decoding error handling (#4294)
REVERT: 738a6f834 ci: move to final release of 3.11 (#4286)
REVERT: 1f187d9a3 Fix char8_t support (#4278)
REVERT: 0e82c3609 fix: add flag for overriding classic Python search values (#4195)
REVERT: ce63bcb98 Fix casts to void* (#4275)
REVERT: 305c47113 fix: Revert pfect args make iterator (#4234)
REVERT: eaa5f7bd4 Revert "feat: add entrypoint for cmake modules dir" (#4270)
REVERT: 251516bce Cleanup casters to release none() to avoid ref counting (#4269)
REVERT: a8f211073 docs: update changelog (#4265)
REVERT: 412918d12 feat: add entrypoint for cmake modules dir (#4258)
REVERT: 895fc6632 ci: update PGI build (old one no longer signed) (#4260)

git-subtree-dir: vendor/pybind11
git-subtree-split: a2e59f0e7065404b44dfe92a28aca47ba1378dc4